'''
Provides the interface for the specific Spinglass algorithm
to be used for word community detection.

To use this algorithm, in the .yaml configuration write the name of this module.
(slicing: type: slicing_spinglass)

The Spinglass algorithm is sensible to weighted edges. These weights
are generated by classes in the weight package. The specific
weighting scheme can be configured in "slicing: weight_calculator:"
attribute of the yaml configuration file. 

@author: Mota
'''
import mm.input.slicing.graph.slicing_graph_based as slicing_graph_based
from mm.input.slicing.graph.weight.factory import factory
from wrapper.iGraphWrapper import iGraphWrapper
import os

class SlicingSpinglass(slicing_graph_based.SlicingGraphBased):
    def __init__(self, slicer_configs):
        super(SlicingSpinglass, self).__init__(slicer_configs)
        self.igraphWrapper = iGraphWrapper(self)
        self.g = self.igraphWrapper.createGraph()
        self.weightcalc = factory(slicer_configs, self.igraphWrapper)
        self.weightcalc.calculateWeights()
        self.wc_des = slicer_configs["graph_community"]['weight_calculator']
        self.debugDir = 'resources/slicing_results/spinglass/'
        self.debugFile = self.debugDir + self.wc_des + ".txt"
        
    def spinglass(self):
        '''
        For some reason the spinglass algorithm does not work is the graph
        has disconnected component. This code just keep largest connected graph
        
        TODO: see why I actually have disconnected components
        '''
        clusters = self.g.clusters()
        subGraphs = clusters.subgraphs()
        maxNodes = 0
        mainGraph = None
        for gr in subGraphs:
            if gr.vcount() >= maxNodes:
                maxNodes = gr.vcount()
                mainGraph = gr
        self.g = mainGraph
        vertexCluster =  self.g.community_spinglass(weights="weight")
        return self.igraphWrapper.getCommunities(vertexCluster)
    
    def run(self):
        communities = self.spinglass()
        if not os.path.exists(self.debugDir):
            os.makedirs(self.debugDir)
        self.print_communities(communities, self.debugFile)
        return communities
    
def construct(config):
    return SlicingSpinglass(config)  
