'''
Provides the interface for the specific Label Propagation algorithm
to be used for word community detection.

To use this algorithm, in the .yaml configuration write the name of this module.
(slicing: type: slicing_label_propagation)

The Label Propagation algorithm is sensible to weighted edges. These weights
are generated by classes in the weight package. The specific
weighting scheme can be configured in "slicing: weight_calculator:"
attribute of the yaml configuration file. 

@author: Mota
'''
import mm.input.slicing.graph.slicing_graph_based as slicing_graph_based
from mm.input.slicing.graph.weight.factory import factory
from wrapper.iGraphWrapper import iGraphWrapper
import os

class SlicingLabelPropagation(slicing_graph_based.SlicingGraphBased):
    def __init__(self, slicer_configs):
        super(SlicingLabelPropagation, self).__init__(slicer_configs)
        self.igraphWrapper = iGraphWrapper(self)
        self.g = self.igraphWrapper.createGraph()
        self.weightcalc = factory(slicer_configs, self.igraphWrapper)
        self.weightcalc.calculateWeights()
        self.wc_des = slicer_configs['weight_calculator']
        
        
    def label_propagation(self):
        vertexCluster =  self.g.community_label_propagation(weights="weight")
        return self.igraphWrapper.getCommunities(vertexCluster)
    
    def run(self):
        communities = self.label_propagation()
        directory = 'slicing_results/label_propagation/'
        if not os.path.exists(directory):
            os.makedirs(directory)
        self.print_communities(communities, directory + self.wc_des + ".txt")
        return communities
    
def construct(config):
    return SlicingLabelPropagation(config)  
