'''
Provides the interface for the specific Spinglass algorithm
to be used for word community detection.

To use this algorithm, in the .yaml configuration write the name of this module.
(slicing: type: slicing_spinglass)

The Spinglass algorithm is sensible to weighted edges. These weights
are generated by classes in the weight package. The specific
weighting scheme can be configured in "slicing: weight_calculator:"
attribute of the yaml configuration file. 

@author: Mota
'''
import mm.input.slicing.graph.slicing_graph_based as slicing_graph_based
from mm.input.slicing.graph.weight.factory import factory
from wrapper.iGraphWrapper import iGraphWrapper
import os

class SlicingSpinglass(slicing_graph_based.SlicingGraphBased):
    def __init__(self, legacy_helper_config_dict):
        super(SlicingSpinglass, self).__init__(legacy_helper_config_dict)
        self.igraphWrapper = iGraphWrapper(self)
        self.g = self.igraphWrapper.createGraph()
        self.weightcalc = factory(legacy_helper_config_dict, self.igraphWrapper)
        self.weightcalc.calculateWeights()
        self.wc_des = legacy_helper_config_dict['weight_calculator']
        
    def spinglass(self):
        vertexCluster =  self.g.community_spinglass(weights="weight")
        return self.igraphWrapper.getCommunities(vertexCluster)
    
    def run(self):
        communities = self.spinglass()
        directory = 'slicing_results/spinglass/'
        if not os.path.exists(directory):
            os.makedirs(directory)
        self.print_communities(communities, directory + self.wc_des + ".txt")
        return communities
    
def construct(config):
    return SlicingSpinglass(config)  
